import { contextBridge, ipcRenderer } from "electron";
import type { IpcEventMap, IpcInvokeMap } from "./src/types/ipc";
import type { PreloadAPI, TradePreloadAPI } from "./src/types/preload";
import { ipcDataBridge } from "./ipc/preloadListeners";
import {
  FEEDBACK_CONTEXT,
  FEEDBACK_SUBMIT,
  INVENTORY_GET,
  INVENTORY_OPEN_FILE,
  INVENTORY_OPEN_ALECA_FRAME_FILE,
  INVENTORY_GET_STATUS,
  INVENTORY_SET_SOURCE,
  INVENTORY_EXPORT,
  INVENTORY_UPDATED,
  INVENTORY_STATUS_UPDATED,
  DB_GET_ITEM_DATABASE,
  ITEM_DB_UPDATED,
  GAME_LOCALE_UPDATED,
  DB_GET_WORLD_STATE,
  DB_GET_RELIC_DATABASE,
  DB_GET_RELIC_DATA_INFO,
  RELIC_DB_UPDATED,
  DROP_SEARCH,
  DROP_ITEM_SOURCES,
  SPAWN_NODES_GET,
  DB_GET_WFM_ITEMS,
  DB_GET_MASTERY,
  DB_GET_CODEX_SCANS,
  PERSONAL_PROFILE_GET,
  PROFILE_ACCOUNT_CHANGED,
  OVERLAY_PLACEMENT_LAYOUT,
  OVERLAY_SAVE_PLACEMENT,
  OVERLAY_SAVE_SCALE,
  WFM_SIGNIN,
  WFM_SIGNOUT,
  WFM_SESSION,
  WFM_GET_ORDERS,
  WFM_GET_CONTRACTS,
  WFM_CREATE_ORDER,
  WFM_UPDATE_ORDER,
  WFM_DELETE_ORDER,
  WFM_CLOSE_ORDER,
  WFM_SET_VISIBLE,
  WFM_SEARCH_ITEMS,
  WFM_LOOKUP_ITEM,
  MARKET_STATS_HISTORY_MERGE,
  WFM_GET_ME,
  WFM_SET_STATUS,
  WFM_PRESENCE_STATE,
  WFM_NOTIFICATION,
  APP_UPDATE_CHECK,
  SYSTEM_CONFIRM,
  APP_UPDATE_STATE,
  APP_UPDATE_DOWNLOAD,
  APP_UPDATE_INSTALL,
  APP_UPDATE_STATUS,
  APP_RUNTIME_INFO,
  SCAN_DEBUG_OPEN_FOLDER,
  LOGS_OPEN_FOLDER,
  LINUX_DISPLAY_GET,
  LINUX_DISPLAY_SET,
  LINUX_CAPTURE_SETUP,
  WINDOW_MINIMIZE,
  WINDOW_MAXIMIZE,
  WINDOW_CLOSE,
  TOGGLE_OVERLAY,
  SIMULATE_RELIC_TRIGGER,
  OVERLAY_THEME_UPDATED,
  OVERLAY_LOCALE_UPDATED,
  OVERLAY_PUSH_RELIC_FILTERS,
  OVERLAY_GET_SETTINGS,
  OVERLAY_EDIT_BEGIN,
  OVERLAY_EDIT_PREVIEW,
  OVERLAY_EDIT_UPDATE,
  OVERLAY_EDIT_END,
  OVERLAY_EDIT_STATE,
  OVERLAY_SET_SETTINGS,
  OVERLAY_GET_DETECTED_UI_SCALE,
  WARFRAME_UI_SCALE_UPDATED,
  RIVEN_SIMILAR_AUCTIONS,
  OPEN_EXTERNAL,
  LOG_WARN,
  NOTIFICATION_HISTORY_GET,
  NOTIFICATION_HISTORY_CLEAR,
  NOTIFICATION_HISTORY_REMOVE,
  NOTIFICATION_TEST,
  NOTIFICATION_HISTORY_ADDED,
  NOTIFICATION_SOUND_GET,
  NOTIFICATION_SOUND_SAVE,
  NOTIFICATION_SOUND_RESET,
  NOTIFICATION_SOUND_PLAY,
  NOTIFICATION_CHANNELS_GET,
  NOTIFICATION_CHANNELS_SET_WEBHOOK,
  NOTIFICATION_CHANNELS_CLEAR_WEBHOOK,
  NOTIFICATION_CHANNELS_SET_SOURCE,
  NOTIFICATION_CHANNELS_SET_GAME_GATE,
  NOTIFICATION_CHANNELS_SET_DISCORD_PING,
  NOTIFICATION_CHANNELS_TEST,
  RANKED_HOTSET_LOAD,
  RANKED_HOTSET_SAVE,
  SNAPSHOT_CACHE_LOAD,
  SNAPSHOT_CACHE_SAVE,
  STATS_GET_HISTORY,
  STATS_GET_CURRENT,
  STATS_IMPORT,
  STATS_GET_TRADES,
  STATS_IMPORT_TRADES,
  TRADE_RECORDED,
  HELPER_GET_STATUS,
  HELPER_RUN_NOW,
  HELPER_DOWNLOAD,
  HELPER_DOWNLOAD_PROGRESS,
  RIVENS_GET,
  RIVENS_GET_WEAPON_NAMES,
  RIVENS_GET_STAT_OPTIONS,
  RIVENS_SEARCH_AUCTIONS,
  RIVENS_GET_BEST_ATTRIBUTES,
  RIVENS_GET_GOOD_ROLL,
  RIVENS_REFRESH_GOOD_ROLLS,
  RIVENS_GRADE_CONTRACTS,
  RIVENS_CREATE_AUCTION,
  RIVENS_UPDATE_AUCTION,
  RIVENS_DELETE_AUCTION,
  WORLD_STATE_FETCH_ERROR,
  ARBI_GET_RUNS,
  ARBI_REFRESH_RUNS,
  ARBI_SET_VITUS,
  ARBI_SET_TAGS,
  ARBI_SET_NOTES,
  ARBI_DELETE_RUN,
  ARBI_DELETE_LOG,
  ARBI_EXPORT_LOG,
  ARBI_IMPORT_LOG,
  ARBI_SAVE_IMAGE,
  ARBI_SHOW_LOG_IN_FOLDER,
  ARBI_RUN_SAVED,
  ARBI_OPEN_RUN,
  PT_GET_RUNS,
  PT_REFRESH_RUNS,
  PT_SET_TAGS,
  PT_SET_NOTES,
  PT_DELETE_RUN,
  PT_DELETE_LOG,
  PT_EXPORT_LOG,
  PT_IMPORT_LOG,
  PT_SHOW_LOG_IN_FOLDER,
  PT_RUN_SAVED,
  LEVEL_CAP_GET,
  LEVEL_CAP_SET_NOTES,
  LEVEL_CAP_ASSIGN_BUILD,
  LEVEL_CAP_CATALOG,
  LEVEL_CAP_ITEM_CONFIGS,
  LEVEL_CAP_MODULAR_ITEMS,
  LEVEL_CAP_CREATE_BUILD,
  LEVEL_CAP_DELETE_BUILD,
  LEVEL_CAP_UPDATE_BUILD,
  LEVEL_CAP_DELETE_RUN,
  LEVEL_CAP_IMPORT_FOLDERS,
  LEVEL_CAP_UPDATE_SETTINGS,
  LEVEL_CAP_PICK_FOLDER,
  LEVEL_CAP_THUMBNAIL,
  LEVEL_CAP_OPEN_SCREENSHOT,
  LEVEL_CAP_UNDERFRAME_DPS,
  LEVEL_CAP_UNDERFRAME_PREWARM,
  LEVEL_CAP_SQUAD_CROP,
  LEVEL_CAP_SCREENSHOT,
  LEVEL_CAP_FIX_SQUADMATE,
  LEVEL_CAP_PORTRAIT_THUMB,
  LEVEL_CAP_LABEL_PORTRAIT,
  LEVEL_CAP_UPDATED,
  LEVEL_CAP_HOTKEY,
  ARBI_SCHED_GET,
  ARBI_SCHED_SET_OCCURRENCE,
  ARBI_SCHED_SET_FAVORITE,
  ARBI_SCHED_SET_LEAD,
  WORKBENCH_ACK_OVERRIDE,
  WORKBENCH_CANCEL_RUN,
  WORKBENCH_EXECUTE_PLAN,
  WORKBENCH_GET_STATE,
  WORKBENCH_PREVIEW_PLAN,
  WORKBENCH_RECONCILE,
  WORKBENCH_RESOLVE_REVIEW,
  WORKBENCH_STATE_EVENT,
  LEDGER_QUERY,
  LEDGER_IMPORT_PREVIEW,
  LEDGER_IMPORT_APPLY,
  LEDGER_UPDATE_EVENT,
  LEDGER_EXPORT,
  POPOUT_OPEN,
  POPOUT_SET_PINNED,
  POPOUT_LIST,
  POPOUT_CLOSE,
  POPOUT_CLOSE_ALL,
  POPOUT_STATE_CHANGED,
  INVENTORY_SELECTION_COMPLETE,
  MARKET_ALERTS_CHANGED,
  MARKET_ALERTS_CLEAR_COOLDOWN,
  MARKET_ALERTS_CLEAR_HITS,
  MARKET_ALERTS_DELETE,
  MARKET_ALERTS_EXPORT,
  MARKET_ALERTS_HITS,
  MARKET_ALERTS_IMPORT,
  MARKET_ALERTS_LIST,
  MARKET_ALERTS_SAVE,
  MARKET_ALERTS_SET_ENABLED,
  MARKET_ALERTS_STATUS,
  MARKET_ALERTS_TEST_FIRE,
  MISSION_REWARDS_GET,
  MISSION_REWARDS_PAGE,
  MISSION_REWARDS_UPDATED,
} from "./config/shared/ipcChannels";

// invoke() is typed any; this wrapper pins each call's args+return to its IpcInvokeMap entry so drift fails typecheck.
const inv =
  <K extends keyof IpcInvokeMap>(channel: string) =>
  (...args: IpcInvokeMap[K]["args"]): Promise<IpcInvokeMap[K]["return"]> =>
    ipcRenderer.invoke(channel, ...args);

// Methods whose wire payload wraps the args in an object.
type Ret<K extends keyof IpcInvokeMap> = Promise<IpcInvokeMap[K]["return"]>;

try {
  contextBridge.exposeInMainWorld("api", {
    platform: process.platform,
    getFeedbackContext: inv<"getFeedbackContext">(FEEDBACK_CONTEXT),
    submitFeedback: inv<"submitFeedback">(FEEDBACK_SUBMIT),

    getInventory: inv<"getInventory">(INVENTORY_GET),
    openInventoryFile: inv<"openInventoryFile">(INVENTORY_OPEN_FILE),
    openAlecaFrameInventoryFile: inv<"openAlecaFrameInventoryFile">(
      INVENTORY_OPEN_ALECA_FRAME_FILE,
    ),
    getInventoryStatus: inv<"getInventoryStatus">(INVENTORY_GET_STATUS),
    setInventorySource: inv<"setInventorySource">(INVENTORY_SET_SOURCE),
    exportInventory: inv<"exportInventory">(INVENTORY_EXPORT),

    getItemDatabase: inv<"getItemDatabase">(DB_GET_ITEM_DATABASE),
    getWorldState: inv<"getWorldState">(DB_GET_WORLD_STATE),
    getRelicDatabase: inv<"getRelicDatabase">(DB_GET_RELIC_DATABASE),
    getRelicDataInfo: inv<"getRelicDataInfo">(DB_GET_RELIC_DATA_INFO),
    getWfmItems: inv<"getWfmItems">(DB_GET_WFM_ITEMS),

    wfmSignIn: inv<"wfmSignIn">(WFM_SIGNIN),
    wfmSignOut: inv<"wfmSignOut">(WFM_SIGNOUT),
    wfmGetSession: inv<"wfmGetSession">(WFM_SESSION),
    wfmGetOrders: inv<"wfmGetOrders">(WFM_GET_ORDERS),
    wfmGetContracts: inv<"wfmGetContracts">(WFM_GET_CONTRACTS),
    wfmSearchItems: (query, limit): Ret<"wfmSearchItems"> =>
      ipcRenderer.invoke(WFM_SEARCH_ITEMS, { query, limit }),
    wfmLookupItemBySlug: (slug): Ret<"wfmLookupItemBySlug"> =>
      ipcRenderer.invoke(WFM_LOOKUP_ITEM, { slug }),
    marketStatsHistoryMerge: (slug, points, mode): Ret<"marketStatsHistoryMerge"> =>
      ipcRenderer.invoke(MARKET_STATS_HISTORY_MERGE, { slug, points, mode }),
    wfmGetMe: inv<"wfmGetMe">(WFM_GET_ME),
    wfmPresenceState: inv<"wfmPresenceState">(WFM_PRESENCE_STATE),

    getMasteryProgress: inv<"getMasteryProgress">(DB_GET_MASTERY),
    getPersonalProfile: inv<"getPersonalProfile">(PERSONAL_PROFILE_GET),
    getCodexScans: inv<"getCodexScans">(DB_GET_CODEX_SCANS),
    getOverlayPlacementLayout: inv<"getOverlayPlacementLayout">(OVERLAY_PLACEMENT_LAYOUT),
    saveOverlayPlacement: inv<"saveOverlayPlacement">(OVERLAY_SAVE_PLACEMENT),
    saveOverlayScale: inv<"saveOverlayScale">(OVERLAY_SAVE_SCALE),
    searchDrops: (query, mode): Ret<"searchDrops"> =>
      ipcRenderer.invoke(DROP_SEARCH, { query, mode }),
    dropSourcesForItem: inv<"dropSourcesForItem">(DROP_ITEM_SOURCES),
    getSpawnNodes: inv<"getSpawnNodes">(SPAWN_NODES_GET),
    confirmDialog: inv<"confirmDialog">(SYSTEM_CONFIRM),
    checkForAppUpdates: inv<"checkForAppUpdates">(APP_UPDATE_CHECK),
    getAppUpdateState: inv<"getAppUpdateState">(APP_UPDATE_STATE),
    downloadAppUpdate: inv<"downloadAppUpdate">(APP_UPDATE_DOWNLOAD),
    installDownloadedUpdate: inv<"installDownloadedUpdate">(APP_UPDATE_INSTALL),
    getAppRuntimeInfo: inv<"getAppRuntimeInfo">(APP_RUNTIME_INFO),
    openScanDebugFolder: inv<"openScanDebugFolder">(SCAN_DEBUG_OPEN_FOLDER),
    openLogFolder: inv<"openLogFolder">(LOGS_OPEN_FOLDER),

    onInventoryUpdated: ipcDataBridge<IpcEventMap["inventory-updated"]>(
      ipcRenderer,
      INVENTORY_UPDATED,
    ),
    onProfileAccountChanged: ipcDataBridge<void>(ipcRenderer, PROFILE_ACCOUNT_CHANGED),
    onInventoryStatusUpdated: ipcDataBridge<IpcEventMap["inventory-status-updated"]>(
      ipcRenderer,
      INVENTORY_STATUS_UPDATED,
    ),
    onItemDbUpdated: ipcDataBridge<IpcEventMap["item-db-updated"]>(ipcRenderer, ITEM_DB_UPDATED),
    onRelicDbUpdated: ipcDataBridge<IpcEventMap["relic-db-updated"]>(ipcRenderer, RELIC_DB_UPDATED),
    onAppUpdateStatus: ipcDataBridge<IpcEventMap["app-update-status"]>(
      ipcRenderer,
      APP_UPDATE_STATUS,
    ),
    onWfmNotification: ipcDataBridge<IpcEventMap["wfm:notification"]>(
      ipcRenderer,
      WFM_NOTIFICATION,
    ),
    onTradeRecorded: ipcDataBridge<IpcEventMap["trade-recorded"]>(ipcRenderer, TRADE_RECORDED),
    onWorldStateFetchError: ipcDataBridge<IpcEventMap["world-state-fetch-error"]>(
      ipcRenderer,
      WORLD_STATE_FETCH_ERROR,
    ),

    minimizeWindow: () => ipcRenderer.send(WINDOW_MINIMIZE),
    maximizeWindow: () => ipcRenderer.send(WINDOW_MAXIMIZE),
    closeWindow: () => ipcRenderer.send(WINDOW_CLOSE),

    toggleOverlay: () => ipcRenderer.send(TOGGLE_OVERLAY),
    simulateRelicTrigger: () => ipcRenderer.send(SIMULATE_RELIC_TRIGGER),
    updateOverlayTheme: (themeVars) => ipcRenderer.send(OVERLAY_THEME_UPDATED, themeVars),
    updateOverlayLocale: (locale) => ipcRenderer.send(OVERLAY_LOCALE_UPDATED, locale),
    updateGameLocale: (locale) => ipcRenderer.send(GAME_LOCALE_UPDATED, locale),
    pushRelicFilters: (filters) => ipcRenderer.send(OVERLAY_PUSH_RELIC_FILTERS, filters),
    getLinuxDisplay: inv<"getLinuxDisplay">(LINUX_DISPLAY_GET),
    setLinuxDisplay: inv<"setLinuxDisplay">(LINUX_DISPLAY_SET),
    setUpLinuxCapture: inv<"setUpLinuxCapture">(LINUX_CAPTURE_SETUP),
    getOverlaySettings: inv<"getOverlaySettings">(OVERLAY_GET_SETTINGS),
    beginOverlayEdit: inv<"beginOverlayEdit">(OVERLAY_EDIT_BEGIN),
    getOverlayPreview: inv<"getOverlayPreview">(OVERLAY_EDIT_PREVIEW),
    updateOverlayEdit: inv<"updateOverlayEdit">(OVERLAY_EDIT_UPDATE),
    endOverlayEdit: inv<"endOverlayEdit">(OVERLAY_EDIT_END),
    onOverlayEditState: ipcDataBridge<IpcEventMap["overlay-edit-state"]>(
      ipcRenderer,
      OVERLAY_EDIT_STATE,
    ),
    setOverlaySettings: inv<"setOverlaySettings">(OVERLAY_SET_SETTINGS),
    getDetectedWarframeUiScale: inv<"getDetectedWarframeUiScale">(OVERLAY_GET_DETECTED_UI_SCALE),

    openExternal: (url) => ipcRenderer.send(OPEN_EXTERNAL, url),
    logWarn: (message, ...args) => ipcRenderer.send(LOG_WARN, message, ...args),

    getNotificationSound: inv<"getNotificationSound">(NOTIFICATION_SOUND_GET),
    saveNotificationSound: inv<"saveNotificationSound">(NOTIFICATION_SOUND_SAVE),
    resetNotificationSound: inv<"resetNotificationSound">(NOTIFICATION_SOUND_RESET),
    getNotificationHistory: inv<"getNotificationHistory">(NOTIFICATION_HISTORY_GET),
    clearNotificationHistory: inv<"clearNotificationHistory">(NOTIFICATION_HISTORY_CLEAR),
    removeNotificationEntry: inv<"removeNotificationEntry">(NOTIFICATION_HISTORY_REMOVE),
    sendTestNotification: inv<"sendTestNotification">(NOTIFICATION_TEST),
    onNotificationHistoryAdded: ipcDataBridge<IpcEventMap["notification-history-added"]>(
      ipcRenderer,
      NOTIFICATION_HISTORY_ADDED,
    ),
    onMarketAlertsChanged: ipcDataBridge<IpcEventMap["market-alerts:changed"]>(
      ipcRenderer,
      MARKET_ALERTS_CHANGED,
    ),
    onNotificationSoundPlay: ipcDataBridge<IpcEventMap["notification-sound-play"]>(
      ipcRenderer,
      NOTIFICATION_SOUND_PLAY,
    ),

    getNotificationChannels: inv<"getNotificationChannels">(NOTIFICATION_CHANNELS_GET),
    setNotificationWebhook: inv<"setNotificationWebhook">(NOTIFICATION_CHANNELS_SET_WEBHOOK),
    clearNotificationWebhook: inv<"clearNotificationWebhook">(NOTIFICATION_CHANNELS_CLEAR_WEBHOOK),
    setNotificationSourceChannels: inv<"setNotificationSourceChannels">(
      NOTIFICATION_CHANNELS_SET_SOURCE,
    ),
    setNotificationGameGate: inv<"setNotificationGameGate">(NOTIFICATION_CHANNELS_SET_GAME_GATE),
    setNotificationDiscordPing: inv<"setNotificationDiscordPing">(
      NOTIFICATION_CHANNELS_SET_DISCORD_PING,
    ),
    testNotificationWebhook: inv<"testNotificationWebhook">(NOTIFICATION_CHANNELS_TEST),

    marketAlertsList: inv<"marketAlertsList">(MARKET_ALERTS_LIST),
    marketAlertsSave: inv<"marketAlertsSave">(MARKET_ALERTS_SAVE),
    marketAlertsDelete: inv<"marketAlertsDelete">(MARKET_ALERTS_DELETE),
    marketAlertsSetEnabled: inv<"marketAlertsSetEnabled">(MARKET_ALERTS_SET_ENABLED),
    marketAlertsClearCooldown: inv<"marketAlertsClearCooldown">(MARKET_ALERTS_CLEAR_COOLDOWN),
    marketAlertsGetHits: inv<"marketAlertsGetHits">(MARKET_ALERTS_HITS),
    marketAlertsClearHits: inv<"marketAlertsClearHits">(MARKET_ALERTS_CLEAR_HITS),
    marketAlertsStatus: inv<"marketAlertsStatus">(MARKET_ALERTS_STATUS),
    marketAlertsTestFire: inv<"marketAlertsTestFire">(MARKET_ALERTS_TEST_FIRE),
    marketAlertsExport: inv<"marketAlertsExport">(MARKET_ALERTS_EXPORT),
    marketAlertsImport: inv<"marketAlertsImport">(MARKET_ALERTS_IMPORT),

    loadRankedHotset: inv<"loadRankedHotset">(RANKED_HOTSET_LOAD),
    saveRankedHotset: inv<"saveRankedHotset">(RANKED_HOTSET_SAVE),
    loadSnapshotCache: inv<"loadSnapshotCache">(SNAPSHOT_CACHE_LOAD),
    saveSnapshotCache: inv<"saveSnapshotCache">(SNAPSHOT_CACHE_SAVE),

    getStatsHistory: inv<"getStatsHistory">(STATS_GET_HISTORY),
    getStatsCurrentSession: inv<"getStatsCurrentSession">(STATS_GET_CURRENT),
    importStatsHistory: inv<"importStatsHistory">(STATS_IMPORT),
    getTradeLog: inv<"getTradeLog">(STATS_GET_TRADES),
    importTradeLog: inv<"importTradeLog">(STATS_IMPORT_TRADES),

    getHelperStatus: inv<"getHelperStatus">(HELPER_GET_STATUS),
    runHelperNow: inv<"runHelperNow">(HELPER_RUN_NOW),
    downloadHelper: inv<"downloadHelper">(HELPER_DOWNLOAD),
    getRivens: inv<"getRivens">(RIVENS_GET),
    getRivenWeaponNames: inv<"getRivenWeaponNames">(RIVENS_GET_WEAPON_NAMES),
    getRivenStatOptions: inv<"getRivenStatOptions">(RIVENS_GET_STAT_OPTIONS),
    searchRivenAuctions: inv<"searchRivenAuctions">(RIVENS_SEARCH_AUCTIONS),
    getRivenBestAttributes: inv<"getRivenBestAttributes">(RIVENS_GET_BEST_ATTRIBUTES),
    getRivenGoodRoll: inv<"getRivenGoodRoll">(RIVENS_GET_GOOD_ROLL),
    refreshRivenGoodRolls: inv<"refreshRivenGoodRolls">(RIVENS_REFRESH_GOOD_ROLLS),
    gradeRivenContracts: inv<"gradeRivenContracts">(RIVENS_GRADE_CONTRACTS),
    onHelperDownloadProgress: ipcDataBridge<IpcEventMap["helper-download-progress"]>(
      ipcRenderer,
      HELPER_DOWNLOAD_PROGRESS,
    ),

    getArbiRuns: inv<"getArbiRuns">(ARBI_GET_RUNS),
    refreshArbiRuns: inv<"refreshArbiRuns">(ARBI_REFRESH_RUNS),
    setArbiRunVitus: inv<"setArbiRunVitus">(ARBI_SET_VITUS),
    setArbiRunTags: inv<"setArbiRunTags">(ARBI_SET_TAGS),
    setArbiRunNotes: inv<"setArbiRunNotes">(ARBI_SET_NOTES),
    deleteArbiRun: inv<"deleteArbiRun">(ARBI_DELETE_RUN),
    deleteArbiRunLog: inv<"deleteArbiRunLog">(ARBI_DELETE_LOG),
    exportArbiRunLog: inv<"exportArbiRunLog">(ARBI_EXPORT_LOG),
    importArbiLog: inv<"importArbiLog">(ARBI_IMPORT_LOG),
    saveArbiRunImage: inv<"saveArbiRunImage">(ARBI_SAVE_IMAGE),
    showArbiRunLogInFolder: inv<"showArbiRunLogInFolder">(ARBI_SHOW_LOG_IN_FOLDER),
    onArbiRunSaved: ipcDataBridge<IpcEventMap["arbi-run-saved"]>(ipcRenderer, ARBI_RUN_SAVED),
    onWarframeUiScaleUpdated: ipcDataBridge<IpcEventMap["warframe-ui-scale-updated"]>(
      ipcRenderer,
      WARFRAME_UI_SCALE_UPDATED,
    ),
    onRivenSimilarAuctions: ipcDataBridge<IpcEventMap["riven-similar-auctions"]>(
      ipcRenderer,
      RIVEN_SIMILAR_AUCTIONS,
    ),
    onArbiOpenRun: ipcDataBridge<IpcEventMap["arbi-open-run"]>(ipcRenderer, ARBI_OPEN_RUN),

    getPtRuns: inv<"getPtRuns">(PT_GET_RUNS),
    refreshPtRuns: inv<"refreshPtRuns">(PT_REFRESH_RUNS),
    setPtRunTags: inv<"setPtRunTags">(PT_SET_TAGS),
    setPtRunNotes: inv<"setPtRunNotes">(PT_SET_NOTES),
    deletePtRun: inv<"deletePtRun">(PT_DELETE_RUN),
    deletePtRunLog: inv<"deletePtRunLog">(PT_DELETE_LOG),
    exportPtRunLog: inv<"exportPtRunLog">(PT_EXPORT_LOG),
    importPtLog: inv<"importPtLog">(PT_IMPORT_LOG),
    showPtRunLogInFolder: inv<"showPtRunLogInFolder">(PT_SHOW_LOG_IN_FOLDER),
    onPtRunSaved: ipcDataBridge<IpcEventMap["pt-run-saved"]>(ipcRenderer, PT_RUN_SAVED),

    getMissionRewards: inv<"getMissionRewards">(MISSION_REWARDS_GET),
    getMissionRewardsPage: inv<"getMissionRewardsPage">(MISSION_REWARDS_PAGE),
    onMissionRewardsUpdated: ipcDataBridge<IpcEventMap["mission-rewards-updated"]>(
      ipcRenderer,
      MISSION_REWARDS_UPDATED,
    ),

    getLevelCap: inv<"getLevelCap">(LEVEL_CAP_GET),
    setLevelCapNotes: inv<"setLevelCapNotes">(LEVEL_CAP_SET_NOTES),
    createLevelCapBuild: inv<"createLevelCapBuild">(LEVEL_CAP_CREATE_BUILD),
    updateLevelCapBuild: inv<"updateLevelCapBuild">(LEVEL_CAP_UPDATE_BUILD),
    deleteLevelCapBuild: inv<"deleteLevelCapBuild">(LEVEL_CAP_DELETE_BUILD),
    assignLevelCapBuild: inv<"assignLevelCapBuild">(LEVEL_CAP_ASSIGN_BUILD),
    getLevelCapCatalog: inv<"getLevelCapCatalog">(LEVEL_CAP_CATALOG),
    getLevelCapItemConfigs: inv<"getLevelCapItemConfigs">(LEVEL_CAP_ITEM_CONFIGS),
    getLevelCapModularItems: inv<"getLevelCapModularItems">(LEVEL_CAP_MODULAR_ITEMS),
    deleteLevelCapRun: inv<"deleteLevelCapRun">(LEVEL_CAP_DELETE_RUN),
    importLevelCapFolders: inv<"importLevelCapFolders">(LEVEL_CAP_IMPORT_FOLDERS),
    updateLevelCapSettings: inv<"updateLevelCapSettings">(LEVEL_CAP_UPDATE_SETTINGS),
    pickLevelCapFolder: inv<"pickLevelCapFolder">(LEVEL_CAP_PICK_FOLDER),
    getLevelCapThumbnail: inv<"getLevelCapThumbnail">(LEVEL_CAP_THUMBNAIL),
    getLevelCapSquadCrop: inv<"getLevelCapSquadCrop">(LEVEL_CAP_SQUAD_CROP),
    getLevelCapScreenshot: inv<"getLevelCapScreenshot">(LEVEL_CAP_SCREENSHOT),
    fixLevelCapSquadmate: inv<"fixLevelCapSquadmate">(LEVEL_CAP_FIX_SQUADMATE),
    getLevelCapPortraitThumb: inv<"getLevelCapPortraitThumb">(LEVEL_CAP_PORTRAIT_THUMB),
    labelLevelCapPortrait: inv<"labelLevelCapPortrait">(LEVEL_CAP_LABEL_PORTRAIT),
    openLevelCapScreenshot: inv<"openLevelCapScreenshot">(LEVEL_CAP_OPEN_SCREENSHOT),
    openUnderframeDps: inv<"openUnderframeDps">(LEVEL_CAP_UNDERFRAME_DPS),
    prewarmUnderframe: inv<"prewarmUnderframe">(LEVEL_CAP_UNDERFRAME_PREWARM),
    onLevelCapUpdated: ipcDataBridge<IpcEventMap["level-cap-updated"]>(
      ipcRenderer,
      LEVEL_CAP_UPDATED,
    ),
    onLevelCapHotkey: ipcDataBridge<IpcEventMap["level-cap-hotkey"]>(ipcRenderer, LEVEL_CAP_HOTKEY),

    workbenchGetState: inv<"workbenchGetState">(WORKBENCH_GET_STATE),
    workbenchPreviewPlan: inv<"workbenchPreviewPlan">(WORKBENCH_PREVIEW_PLAN),
    workbenchCancelRun: inv<"workbenchCancelRun">(WORKBENCH_CANCEL_RUN),
    workbenchAcknowledgeOverride: inv<"workbenchAcknowledgeOverride">(WORKBENCH_ACK_OVERRIDE),
    workbenchReconcile: inv<"workbenchReconcile">(WORKBENCH_RECONCILE),
    workbenchResolveReview: inv<"workbenchResolveReview">(WORKBENCH_RESOLVE_REVIEW),
    onWorkbenchState: ipcDataBridge<IpcEventMap["workbench-state"]>(
      ipcRenderer,
      WORKBENCH_STATE_EVENT,
    ),

    ledgerQuery: inv<"ledgerQuery">(LEDGER_QUERY),
    ledgerImportPreview: inv<"ledgerImportPreview">(LEDGER_IMPORT_PREVIEW),
    ledgerImportApply: inv<"ledgerImportApply">(LEDGER_IMPORT_APPLY),
    ledgerUpdateEvent: inv<"ledgerUpdateEvent">(LEDGER_UPDATE_EVENT),
    ledgerExport: inv<"ledgerExport">(LEDGER_EXPORT),
    popoutOpen: inv<"popoutOpen">(POPOUT_OPEN),
    popoutSetPinned: inv<"popoutSetPinned">(POPOUT_SET_PINNED),
    popoutList: inv<"popoutList">(POPOUT_LIST),
    popoutClose: inv<"popoutClose">(POPOUT_CLOSE),
    popoutCloseAll: inv<"popoutCloseAll">(POPOUT_CLOSE_ALL),
    onPopoutStateChanged: ipcDataBridge<IpcEventMap["popout-state-changed"]>(
      ipcRenderer,
      POPOUT_STATE_CHANGED,
    ),

    getArbiSchedule: inv<"getArbiSchedule">(ARBI_SCHED_GET),
    setArbiScheduleOccurrence: inv<"setArbiScheduleOccurrence">(ARBI_SCHED_SET_OCCURRENCE),
    setArbiScheduleFavorite: inv<"setArbiScheduleFavorite">(ARBI_SCHED_SET_FAVORITE),
    setArbiScheduleLead: inv<"setArbiScheduleLead">(ARBI_SCHED_SET_LEAD),

    notifySelectionComplete: inv<"notifySelectionComplete">(INVENTORY_SELECTION_COMPLETE),
  } satisfies PreloadAPI);

  contextBridge.exposeInMainWorld("tradeApi", {
    wfmCreateOrder: inv<"wfmCreateOrder">(WFM_CREATE_ORDER),
    wfmUpdateOrder: (orderId, updates): Ret<"wfmUpdateOrder"> =>
      ipcRenderer.invoke(WFM_UPDATE_ORDER, { orderId, updates }),
    wfmDeleteOrder: (orderId): Ret<"wfmDeleteOrder"> =>
      ipcRenderer.invoke(WFM_DELETE_ORDER, { orderId }),
    wfmCloseOrder: (orderId, quantity): Ret<"wfmCloseOrder"> =>
      ipcRenderer.invoke(WFM_CLOSE_ORDER, { orderId, quantity }),
    wfmSetVisible: (orderIds, visible): Ret<"wfmSetVisible"> =>
      ipcRenderer.invoke(WFM_SET_VISIBLE, { orderIds, visible }),
    wfmSetStatus: (status): Ret<"wfmSetStatus"> => ipcRenderer.invoke(WFM_SET_STATUS, { status }),
    createRivenAuction: inv<"createRivenAuction">(RIVENS_CREATE_AUCTION),
    updateRivenAuction: inv<"updateRivenAuction">(RIVENS_UPDATE_AUCTION),
    deleteRivenAuction: inv<"deleteRivenAuction">(RIVENS_DELETE_AUCTION),
    workbenchExecutePlan: inv<"workbenchExecutePlan">(WORKBENCH_EXECUTE_PLAN),
  } satisfies TradePreloadAPI);
} catch (err) {
  console.error("[Preload] FATAL: contextBridge.exposeInMainWorld failed:", err);
}
