// Generated by scripts/build-archon-shard-catalog.mjs, do not edit.
// Source: warframe-worldstate-data archonShards.json (WFCD, MIT).

interface ArchonShardEffect {
  /** Socket colour as the inventory writes it; _MYTHIC is tauforged. */
  color: string;
  type: string;
  /** English effect text at that shard's strength. */
  effect: string;
}

export const ARCHON_SHARD_EFFECTS: readonly ArchonShardEffect[] = Object.freeze([
  {
    color: "ACC_BLUE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeArmourMax",
    effect: "+150 Armor",
  },
  {
    color: "ACC_BLUE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeEnergyMax",
    effect: "+50 Energy Max",
  },
  {
    color: "ACC_BLUE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeHealthMax",
    effect: "+150% Health",
  },
  {
    color: "ACC_BLUE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeRegen",
    effect: "+5 Health/s Regenerated",
  },
  {
    color: "ACC_BLUE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeShieldMax",
    effect: "+150 Shield Capacity",
  },
  {
    color: "ACC_BLUE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeArmourMaxMythic",
    effect: "+225 Armor",
  },
  {
    color: "ACC_BLUE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeEnergyMaxMythic",
    effect: "+75 Energy Max",
  },
  {
    color: "ACC_BLUE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeHealthMaxMythic",
    effect: "+225% Health",
  },
  {
    color: "ACC_BLUE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeRegenMythic",
    effect: "+7.5 Health/s Regenerated",
  },
  {
    color: "ACC_BLUE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeShieldMaxMythic",
    effect: "+225 Shield Capacity",
  },
  {
    color: "ACC_GREEN",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCorrosiveDamageBoost",
    effect: "Gain +10% Ability Damage on enemies affected by Corrosion Status.",
  },
  {
    color: "ACC_GREEN",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCorrosiveStack",
    effect: "Increase max stacks of Corrosion Status by +2.",
  },
  {
    color: "ACC_GREEN",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeToxinDamage",
    effect: "Toxin Status Effects deal +30% more damage.",
  },
  {
    color: "ACC_GREEN",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeToxinHeal",
    effect: "Recover +2 Health each time enemies are damaged by a Toxin Status Effect.",
  },
  {
    color: "ACC_GREEN_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCorrosiveDamageBoostMythic",
    effect: "Gain +15% Ability Damage on enemies affected by Corrosion Status.",
  },
  {
    color: "ACC_GREEN_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCorrosiveStackMythic",
    effect: "Increase max stacks of Corrosion Status by +3.",
  },
  {
    color: "ACC_GREEN_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeToxinDamageMythic",
    effect: "Toxin Status Effects deal +45% more damage.",
  },
  {
    color: "ACC_GREEN_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeToxinHealMythic",
    effect: "Recover +3 Health each time enemies are damaged by a Toxin Status Effect.",
  },
  {
    color: "ACC_ORANGE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeBlastProc",
    effect: "Regenerate +5 Shields when you kill an enemy with Blast Damage.",
  },
  {
    color: "ACC_ORANGE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeHPBoostFromImpact",
    effect: "Gain 2 Health per enemy killed with Blast Damage. Max 450 Health.",
  },
  {
    color: "ACC_ORANGE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeRadiationDamageBoost",
    effect: "Gain +10% Ability Damage on enemies affected by Radiation Status.",
  },
  {
    color: "ACC_ORANGE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWeaponCritBoostFromHeat",
    effect:
      "Increase Secondary Critical Chance by 1% every time you kill an enemy affected by Heat Status. Max 50%.",
  },
  {
    color: "ACC_ORANGE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeBlastProcMythic",
    effect: "Regenerate +7.5 Shields when you kill an enemy with Blast Damage",
  },
  {
    color: "ACC_ORANGE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeHPBoostFromImpactMythic",
    effect: "Gain +2 Health per enemy killed with Blast Damage (Max 450 Health)",
  },
  {
    color: "ACC_ORANGE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeRadiationDamageBoostMythic",
    effect: "Gain +15% Ability Damage on enemies affected by Radiation Status.",
  },
  {
    color: "ACC_ORANGE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWeaponCritBoostFromHeatMythic",
    effect:
      "Increase Secondary Critical Chance by 1.5% every time you kill an enemy affected by Heat Status. Max 75%",
  },
  {
    color: "ACC_PURPLE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeEquilibrium",
    effect: "Health pickups give +20% Energy. Energy pickups give +20% Health.",
  },
  {
    color: "ACC_PURPLE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCritDamageBoost",
    effect:
      "Gain +25% Melee Critical Damage. When max Energy is over 500, the damage boost doubles.",
  },
  {
    color: "ACC_PURPLE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeElectricDamage",
    effect:
      "Gain +30% Primary Electricity Damage. Gain an additional +10% per Crimson, Azure, or Violet Archon Shard equipped.",
  },
  {
    color: "ACC_PURPLE",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeElectricDamageBoost",
    effect: "Gain +10% Ability Damage on enemies affected by Electricity Status.",
  },
  {
    color: "ACC_PURPLE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeEquilibriumMythic",
    effect: "Health pickups give +30% Energy. Energy pickups give +30% Health.",
  },
  {
    color: "ACC_PURPLE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCritDamageBoostMythic",
    effect:
      "Gain +37.5% Melee Critical Damage. When max Energy is over 500, the damage boost doubles.",
  },
  {
    color: "ACC_PURPLE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeElectricDamageBoostMythic",
    effect: "Gain +15% Ability Damage on enemies affected by Electricity Status.",
  },
  {
    color: "ACC_PURPLE_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeElectricDamageMythic",
    effect:
      "Gain +45% Primary Electricity Damage. Gain an additional +15% per Crimson, Azure, or Violet Archon Shard equipped.",
  },
  {
    color: "ACC_RED",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeMeleeCritDamage",
    effect: "+25% Melee Critical Damage",
  },
  {
    color: "ACC_RED",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradePrimaryStatusChance",
    effect: "+25% Primary Status Chance",
  },
  {
    color: "ACC_RED",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeSecondaryCritChance",
    effect: "+25% Secondary Critical Chance",
  },
  {
    color: "ACC_RED",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeAbilityDuration",
    effect: "+10% Ability Duration",
  },
  {
    color: "ACC_RED",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeAbilityStrength",
    effect: "10% Ability Strength",
  },
  {
    color: "ACC_RED_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeMeleeCritDamageMythic",
    effect: "+37.5% Melee Critical Damage",
  },
  {
    color: "ACC_RED_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradePrimaryStatusChanceMythic",
    effect: "+37.5% Primary Status Chance",
  },
  {
    color: "ACC_RED_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeSecondaryCritChanceMythic",
    effect: "+37.5% Secondary Critical Chance",
  },
  {
    color: "ACC_RED_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeAbilityDurationMythic",
    effect: "+15% Ability Duration",
  },
  {
    color: "ACC_RED_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeAbilityStrengthMythic",
    effect: "15% Ability Strength",
  },
  {
    color: "ACC_YELLOW",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCastingSpeed",
    effect: "+25% Casting Speed",
  },
  {
    color: "ACC_YELLOW",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeGlobeEffectEnergy",
    effect: "+50% Effectiveness on Enery Orbs",
  },
  {
    color: "ACC_YELLOW",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeGlobeEffectHealth",
    effect: "+100% Effectiveness on Health Orbs",
  },
  {
    color: "ACC_YELLOW",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeParkourVelocity",
    effect: "+15% Parkour Velocity",
  },
  {
    color: "ACC_YELLOW",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeStartingEnergy",
    effect: "+30% Maximum Energy is filled on spawn",
  },
  {
    color: "ACC_YELLOW_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeCastingSpeedMythic",
    effect: "+37.5% Casting Speed",
  },
  {
    color: "ACC_YELLOW_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeGlobeEffectEnergyMythic",
    effect: "+75% Effectiveness on Enery Orbs",
  },
  {
    color: "ACC_YELLOW_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeGlobeEffectHealthMythic",
    effect: "+150% Effectiveness on Health Orbs",
  },
  {
    color: "ACC_YELLOW_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeParkourVelocityMythic",
    effect: "+22.5% Parkour Velocity",
  },
  {
    color: "ACC_YELLOW_MYTHIC",
    type: "/Lotus/Upgrades/Invigorations/ArchonCrystalUpgrades/ArchonCrystalUpgradeWarframeStartingEnergyMythic",
    effect: "+45% Maximum Energy is filled on spawn",
  },
]);
